-- ============================================================
-- SIMULACRO FINAL — 45 preguntas reales del ICFES (Tabla 17)
-- ============================================================
-- Reemplaza por completo el quiz viejo de 8 preguntas del Módulo 8.
-- Distribución oficial: Parte 1=5, Parte 2=5, Parte 3=5, Parte 4=8,
-- Parte 5=7, Parte 6=5, Parte 7=10 (total 45), cada parte en su
-- formato real: avisos (4 op.), banco de 8 palabras, diálogos (3 op.),
-- texto con espacios básico (4 op.), lectura literal (3 op.), lectura
-- inferencial (4 op.), texto con espacios avanzado (4 op.).
--
-- Requiere haber corrido antes: seed-pre-icfes-modules.sql,
-- quiz-content-pre-icfes.sql (crea el quiz viejo, que este script
-- reemplaza). Mantiene el mismo régimen de examen de certificación:
-- 75/100 para pasar, 3 intentos, 24h de espera entre intentos.
-- Seguro de correr varias veces.
-- ============================================================


delete from public.quiz_questions
where quiz_id in (
  select qz.id from public.quizzes qz
  join public.modules m on m.id = qz.module_id
  join public.courses c on c.id = m.course_id
  where c.slug = 'pre-icfes' and m.title = 'Simulacro final' and qz.stage = 'main'
);

insert into public.quizzes (module_id, title, passing_score, is_final, max_attempts, cooldown_hours, stage)
select m.id, 'Simulacro final — Examen de certificación (45 preguntas)', 75, true, 3, 24, 'main'
from public.modules m join public.courses c on c.id = m.course_id
where c.slug = 'pre-icfes' and m.title = 'Simulacro final'
on conflict (module_id, stage) do update set title = excluded.title, passing_score = excluded.passing_score, is_final = excluded.is_final, max_attempts = excluded.max_attempts, cooldown_hours = excluded.cooldown_hours;

insert into public.quiz_questions (quiz_id, order_index, prompt)
select qz.id, v.order_index, v.prompt
from public.quizzes qz join public.modules m on m.id = qz.module_id join public.courses c on c.id = m.course_id
cross join (values
  (0, '<div class=''sim-part-tag''>Parte 1 de 7 — Avisos y vocabulario</div><p>Ves el aviso <strong>"EMPLOYEES MUST WASH HANDS BEFORE RETURNING TO WORK"</strong> en el baño de un restaurante. ¿Qué exige este aviso?</p>'),
  (1, '<div class=''sim-part-tag''>Parte 1 de 7 — Avisos y vocabulario</div><p>Un letrero en un aeropuerto dice <strong>"FLIGHT DELAYED — NEW BOARDING TIME: 3:45 PM"</strong>. ¿Qué información da este aviso?</p>'),
  (2, '<div class=''sim-part-tag''>Parte 1 de 7 — Avisos y vocabulario</div><p>En la entrada de una piscina ves <strong>"NO DIVING — SHALLOW WATER"</strong>. ¿Qué NO deberías hacer?</p>'),
  (3, '<div class=''sim-part-tag''>Parte 1 de 7 — Avisos y vocabulario</div><p>Un aviso en una biblioteca dice <strong>"SILENCE PLEASE — STUDY AREA"</strong>. ¿Qué comportamiento pide este aviso?</p>'),
  (4, '<div class=''sim-part-tag''>Parte 1 de 7 — Avisos y vocabulario</div><p>Ves <strong>"OUT OF ORDER — USE OTHER ENTRANCE"</strong> pegado en una puerta automática de un centro comercial. ¿Qué deberías hacer?</p>'),
  (5, '<div class=''sim-part-tag''>Parte 2 de 7 — Relación de enunciados (banco de 8 palabras)</div><p style=''font-size:13px;color:var(--muted);margin-bottom:8px;''>Banco (A–H): menu, brochure, invoice, schedule, voucher, itinerary, receipt, certificate — cada palabra se usa una sola vez, 3 quedan sin usar.</p><p><strong>Enunciado:</strong> "This document lists the exact times of your flights and hotel stays during a trip."</p>'),
  (6, '<div class=''sim-part-tag''>Parte 2 de 7 — Relación de enunciados (banco de 8 palabras)</div><p style=''font-size:13px;color:var(--muted);margin-bottom:8px;''>Banco (A–H): menu, brochure, invoice, schedule, voucher, itinerary, receipt, certificate — cada palabra se usa una sola vez, 3 quedan sin usar.</p><p><strong>Enunciado:</strong> "Restaurants give you this list to choose your food and drinks."</p>'),
  (7, '<div class=''sim-part-tag''>Parte 2 de 7 — Relación de enunciados (banco de 8 palabras)</div><p style=''font-size:13px;color:var(--muted);margin-bottom:8px;''>Banco (A–H): menu, brochure, invoice, schedule, voucher, itinerary, receipt, certificate — cada palabra se usa una sola vez, 3 quedan sin usar.</p><p><strong>Enunciado:</strong> "You receive this small paper as proof after you have already paid for something."</p>'),
  (8, '<div class=''sim-part-tag''>Parte 2 de 7 — Relación de enunciados (banco de 8 palabras)</div><p style=''font-size:13px;color:var(--muted);margin-bottom:8px;''>Banco (A–H): menu, brochure, invoice, schedule, voucher, itinerary, receipt, certificate — cada palabra se usa una sola vez, 3 quedan sin usar.</p><p><strong>Enunciado:</strong> "A travel agency gives you this paper that you can exchange for a free hotel night or a discount."</p>'),
  (9, '<div class=''sim-part-tag''>Parte 2 de 7 — Relación de enunciados (banco de 8 palabras)</div><p style=''font-size:13px;color:var(--muted);margin-bottom:8px;''>Banco (A–H): menu, brochure, invoice, schedule, voucher, itinerary, receipt, certificate — cada palabra se usa una sola vez, 3 quedan sin usar.</p><p><strong>Enunciado:</strong> "Schools give you this official document to prove you finished a course."</p>'),
  (10, '<div class=''sim-part-tag''>Parte 3 de 7 — Diálogos y coherencia conversacional</div><p>"Do you want to join us for lunch?"</p>'),
  (11, '<div class=''sim-part-tag''>Parte 3 de 7 — Diálogos y coherencia conversacional</div><p>"I can''t find my keys anywhere."</p>'),
  (12, '<div class=''sim-part-tag''>Parte 3 de 7 — Diálogos y coherencia conversacional</div><p>"You look tired today."</p>'),
  (13, '<div class=''sim-part-tag''>Parte 3 de 7 — Diálogos y coherencia conversacional</div><p>"What''s your favorite subject at school?"</p>'),
  (14, '<div class=''sim-part-tag''>Parte 3 de 7 — Diálogos y coherencia conversacional</div><p>"Could you turn down the music, please?"</p>'),
  (15, '<div class=''sim-part-tag''>Parte 4 de 7 — Texto con espacios (nivel básico)</div><div class=''cloze-passage''>Last weekend, my brother and I went <mark>___(1)___</mark> our grandmother''s house in the countryside. We arrived ___(2)___ ten in the morning and helped her ___(3)___ the garden. She showed us how ___(4)___ plant tomatoes and beans. At noon, we had lunch together and talked about ___(5)___ childhood memories. In the afternoon, my brother played football with ___(6)___ friends from the village while I read a book ___(7)___ the porch. Before we left, our grandmother gave each of us a small basket ___(8)___ fresh vegetables.</div><p style=''margin-top:8px;''><strong>Elige la opción correcta para el espacio (1).</strong></p>'),
  (16, '<div class=''sim-part-tag''>Parte 4 de 7 — Texto con espacios (nivel básico)</div><div class=''cloze-passage''>Last weekend, my brother and I went ___(1)___ our grandmother''s house in the countryside. We arrived <mark>___(2)___</mark> ten in the morning and helped her ___(3)___ the garden. She showed us how ___(4)___ plant tomatoes and beans. At noon, we had lunch together and talked about ___(5)___ childhood memories. In the afternoon, my brother played football with ___(6)___ friends from the village while I read a book ___(7)___ the porch. Before we left, our grandmother gave each of us a small basket ___(8)___ fresh vegetables.</div><p style=''margin-top:8px;''><strong>Elige la opción correcta para el espacio (2).</strong></p>'),
  (17, '<div class=''sim-part-tag''>Parte 4 de 7 — Texto con espacios (nivel básico)</div><div class=''cloze-passage''>Last weekend, my brother and I went ___(1)___ our grandmother''s house in the countryside. We arrived ___(2)___ ten in the morning and helped her <mark>___(3)___</mark> the garden. She showed us how ___(4)___ plant tomatoes and beans. At noon, we had lunch together and talked about ___(5)___ childhood memories. In the afternoon, my brother played football with ___(6)___ friends from the village while I read a book ___(7)___ the porch. Before we left, our grandmother gave each of us a small basket ___(8)___ fresh vegetables.</div><p style=''margin-top:8px;''><strong>Elige la opción correcta para el espacio (3).</strong></p>'),
  (18, '<div class=''sim-part-tag''>Parte 4 de 7 — Texto con espacios (nivel básico)</div><div class=''cloze-passage''>Last weekend, my brother and I went ___(1)___ our grandmother''s house in the countryside. We arrived ___(2)___ ten in the morning and helped her ___(3)___ the garden. She showed us how <mark>___(4)___</mark> plant tomatoes and beans. At noon, we had lunch together and talked about ___(5)___ childhood memories. In the afternoon, my brother played football with ___(6)___ friends from the village while I read a book ___(7)___ the porch. Before we left, our grandmother gave each of us a small basket ___(8)___ fresh vegetables.</div><p style=''margin-top:8px;''><strong>Elige la opción correcta para el espacio (4).</strong></p>'),
  (19, '<div class=''sim-part-tag''>Parte 4 de 7 — Texto con espacios (nivel básico)</div><div class=''cloze-passage''>Last weekend, my brother and I went ___(1)___ our grandmother''s house in the countryside. We arrived ___(2)___ ten in the morning and helped her ___(3)___ the garden. She showed us how ___(4)___ plant tomatoes and beans. At noon, we had lunch together and talked about <mark>___(5)___</mark> childhood memories. In the afternoon, my brother played football with ___(6)___ friends from the village while I read a book ___(7)___ the porch. Before we left, our grandmother gave each of us a small basket ___(8)___ fresh vegetables.</div><p style=''margin-top:8px;''><strong>Elige la opción correcta para el espacio (5).</strong></p>'),
  (20, '<div class=''sim-part-tag''>Parte 4 de 7 — Texto con espacios (nivel básico)</div><div class=''cloze-passage''>Last weekend, my brother and I went ___(1)___ our grandmother''s house in the countryside. We arrived ___(2)___ ten in the morning and helped her ___(3)___ the garden. She showed us how ___(4)___ plant tomatoes and beans. At noon, we had lunch together and talked about ___(5)___ childhood memories. In the afternoon, my brother played football with <mark>___(6)___</mark> friends from the village while I read a book ___(7)___ the porch. Before we left, our grandmother gave each of us a small basket ___(8)___ fresh vegetables.</div><p style=''margin-top:8px;''><strong>Elige la opción correcta para el espacio (6).</strong></p>'),
  (21, '<div class=''sim-part-tag''>Parte 4 de 7 — Texto con espacios (nivel básico)</div><div class=''cloze-passage''>Last weekend, my brother and I went ___(1)___ our grandmother''s house in the countryside. We arrived ___(2)___ ten in the morning and helped her ___(3)___ the garden. She showed us how ___(4)___ plant tomatoes and beans. At noon, we had lunch together and talked about ___(5)___ childhood memories. In the afternoon, my brother played football with ___(6)___ friends from the village while I read a book <mark>___(7)___</mark> the porch. Before we left, our grandmother gave each of us a small basket ___(8)___ fresh vegetables.</div><p style=''margin-top:8px;''><strong>Elige la opción correcta para el espacio (7).</strong></p>'),
  (22, '<div class=''sim-part-tag''>Parte 4 de 7 — Texto con espacios (nivel básico)</div><div class=''cloze-passage''>Last weekend, my brother and I went ___(1)___ our grandmother''s house in the countryside. We arrived ___(2)___ ten in the morning and helped her ___(3)___ the garden. She showed us how ___(4)___ plant tomatoes and beans. At noon, we had lunch together and talked about ___(5)___ childhood memories. In the afternoon, my brother played football with ___(6)___ friends from the village while I read a book ___(7)___ the porch. Before we left, our grandmother gave each of us a small basket <mark>___(8)___</mark> fresh vegetables.</div><p style=''margin-top:8px;''><strong>Elige la opción correcta para el espacio (8).</strong></p>'),
  (23, '<div class=''sim-part-tag''>Parte 5 de 7 — Lectura literal</div><div class=''reading-passage''><p>Camila Torres was born in a small town in Colombia in 2001. When she was ten years old, she moved with her family to Bogotá so her parents could find better jobs. At school, Camila always loved mathematics and often stayed after class to solve extra problems with her teacher. In 2019, she won first place in a national mathematics competition for high school students. After finishing school, she received a scholarship to study engineering at a public university. Today, Camila works as a volunteer teacher on weekends, helping children in her old neighborhood learn math for free.</p></div><p style=''margin-top:8px;''><strong>Where was Camila Torres born?</strong></p>'),
  (24, '<div class=''sim-part-tag''>Parte 5 de 7 — Lectura literal</div><div class=''reading-passage''><p>Camila Torres was born in a small town in Colombia in 2001. When she was ten years old, she moved with her family to Bogotá so her parents could find better jobs. At school, Camila always loved mathematics and often stayed after class to solve extra problems with her teacher. In 2019, she won first place in a national mathematics competition for high school students. After finishing school, she received a scholarship to study engineering at a public university. Today, Camila works as a volunteer teacher on weekends, helping children in her old neighborhood learn math for free.</p></div><p style=''margin-top:8px;''><strong>How old was Camila when she moved to Bogotá?</strong></p>'),
  (25, '<div class=''sim-part-tag''>Parte 5 de 7 — Lectura literal</div><div class=''reading-passage''><p>Camila Torres was born in a small town in Colombia in 2001. When she was ten years old, she moved with her family to Bogotá so her parents could find better jobs. At school, Camila always loved mathematics and often stayed after class to solve extra problems with her teacher. In 2019, she won first place in a national mathematics competition for high school students. After finishing school, she received a scholarship to study engineering at a public university. Today, Camila works as a volunteer teacher on weekends, helping children in her old neighborhood learn math for free.</p></div><p style=''margin-top:8px;''><strong>Why did Camila''s family move to Bogotá?</strong></p>'),
  (26, '<div class=''sim-part-tag''>Parte 5 de 7 — Lectura literal</div><div class=''reading-passage''><p>Camila Torres was born in a small town in Colombia in 2001. When she was ten years old, she moved with her family to Bogotá so her parents could find better jobs. At school, Camila always loved mathematics and often stayed after class to solve extra problems with her teacher. In 2019, she won first place in a national mathematics competition for high school students. After finishing school, she received a scholarship to study engineering at a public university. Today, Camila works as a volunteer teacher on weekends, helping children in her old neighborhood learn math for free.</p></div><p style=''margin-top:8px;''><strong>What subject did Camila love at school?</strong></p>'),
  (27, '<div class=''sim-part-tag''>Parte 5 de 7 — Lectura literal</div><div class=''reading-passage''><p>Camila Torres was born in a small town in Colombia in 2001. When she was ten years old, she moved with her family to Bogotá so her parents could find better jobs. At school, Camila always loved mathematics and often stayed after class to solve extra problems with her teacher. In 2019, she won first place in a national mathematics competition for high school students. After finishing school, she received a scholarship to study engineering at a public university. Today, Camila works as a volunteer teacher on weekends, helping children in her old neighborhood learn math for free.</p></div><p style=''margin-top:8px;''><strong>What did Camila win in 2019?</strong></p>'),
  (28, '<div class=''sim-part-tag''>Parte 5 de 7 — Lectura literal</div><div class=''reading-passage''><p>Camila Torres was born in a small town in Colombia in 2001. When she was ten years old, she moved with her family to Bogotá so her parents could find better jobs. At school, Camila always loved mathematics and often stayed after class to solve extra problems with her teacher. In 2019, she won first place in a national mathematics competition for high school students. After finishing school, she received a scholarship to study engineering at a public university. Today, Camila works as a volunteer teacher on weekends, helping children in her old neighborhood learn math for free.</p></div><p style=''margin-top:8px;''><strong>What did Camila study after finishing school?</strong></p>'),
  (29, '<div class=''sim-part-tag''>Parte 5 de 7 — Lectura literal</div><div class=''reading-passage''><p>Camila Torres was born in a small town in Colombia in 2001. When she was ten years old, she moved with her family to Bogotá so her parents could find better jobs. At school, Camila always loved mathematics and often stayed after class to solve extra problems with her teacher. In 2019, she won first place in a national mathematics competition for high school students. After finishing school, she received a scholarship to study engineering at a public university. Today, Camila works as a volunteer teacher on weekends, helping children in her old neighborhood learn math for free.</p></div><p style=''margin-top:8px;''><strong>What does Camila do today on weekends?</strong></p>'),
  (30, '<div class=''sim-part-tag''>Parte 6 de 7 — Lectura inferencial</div><div class=''reading-passage''><p>For millions of people around the world, having a pet is much more than a hobby. Dogs, cats, and even smaller animals like rabbits or birds become part of the family almost immediately. Many pet owners say that coming home to a wagging tail or a soft purring sound helps them forget a stressful day at work. Scientists have also found that spending time with animals can lower stress hormones and even improve heart health. Still, taking care of a pet is a serious commitment: it requires time, money, and patience, especially during the first few months. Despite the extra responsibility, most owners agree that the emotional connection they build with their pet makes every challenge worth it.</p></div><p style=''margin-top:8px;''><strong>What is the writer mainly trying to do in this text?</strong></p>'),
  (31, '<div class=''sim-part-tag''>Parte 6 de 7 — Lectura inferencial</div><div class=''reading-passage''><p>For millions of people around the world, having a pet is much more than a hobby. Dogs, cats, and even smaller animals like rabbits or birds become part of the family almost immediately. Many pet owners say that coming home to a wagging tail or a soft purring sound helps them forget a stressful day at work. Scientists have also found that spending time with animals can lower stress hormones and even improve heart health. Still, taking care of a pet is a serious commitment: it requires time, money, and patience, especially during the first few months. Despite the extra responsibility, most owners agree that the emotional connection they build with their pet makes every challenge worth it.</p></div><p style=''margin-top:8px;''><strong>What can be inferred about pet owners'' first few months with a new pet?</strong></p>'),
  (32, '<div class=''sim-part-tag''>Parte 6 de 7 — Lectura inferencial</div><div class=''reading-passage''><p>For millions of people around the world, having a pet is much more than a hobby. Dogs, cats, and even smaller animals like rabbits or birds become part of the family almost immediately. Many pet owners say that coming home to a wagging tail or a soft purring sound helps them forget a stressful day at work. Scientists have also found that spending time with animals can lower stress hormones and even improve heart health. Still, taking care of a pet is a serious commitment: it requires time, money, and patience, especially during the first few months. Despite the extra responsibility, most owners agree that the emotional connection they build with their pet makes every challenge worth it.</p></div><p style=''margin-top:8px;''><strong>According to the text, what does the writer suggest about the relationship between people and pets?</strong></p>'),
  (33, '<div class=''sim-part-tag''>Parte 6 de 7 — Lectura inferencial</div><div class=''reading-passage''><p>For millions of people around the world, having a pet is much more than a hobby. Dogs, cats, and even smaller animals like rabbits or birds become part of the family almost immediately. Many pet owners say that coming home to a wagging tail or a soft purring sound helps them forget a stressful day at work. Scientists have also found that spending time with animals can lower stress hormones and even improve heart health. Still, taking care of a pet is a serious commitment: it requires time, money, and patience, especially during the first few months. Despite the extra responsibility, most owners agree that the emotional connection they build with their pet makes every challenge worth it.</p></div><p style=''margin-top:8px;''><strong>What tone does the writer use when discussing the responsibilities of owning a pet?</strong></p>'),
  (34, '<div class=''sim-part-tag''>Parte 6 de 7 — Lectura inferencial</div><div class=''reading-passage''><p>For millions of people around the world, having a pet is much more than a hobby. Dogs, cats, and even smaller animals like rabbits or birds become part of the family almost immediately. Many pet owners say that coming home to a wagging tail or a soft purring sound helps them forget a stressful day at work. Scientists have also found that spending time with animals can lower stress hormones and even improve heart health. Still, taking care of a pet is a serious commitment: it requires time, money, and patience, especially during the first few months. Despite the extra responsibility, most owners agree that the emotional connection they build with their pet makes every challenge worth it.</p></div><p style=''margin-top:8px;''><strong>Why does the writer likely mention scientific findings about stress hormones?</strong></p>'),
  (35, '<div class=''sim-part-tag''>Parte 7 de 7 — Texto con espacios (nivel avanzado)</div><div class=''cloze-passage''>In recent years, renewable energy sources such as solar and wind power <mark>___(1)___</mark> become more affordable than ever before. ___(2)___ fossil fuels still dominate global energy production, many countries are investing heavily in clean alternatives. Governments ___(3)___ introduced new policies to encourage citizens and businesses to reduce their carbon footprint. ___(4)___, some industries continue to resist these changes because of the high initial costs. ___(5)___ these obstacles, experts believe that renewable energy will eventually replace most fossil fuels. Critics argue, ___(6)___, that the transition should happen faster to prevent further damage to the environment. Communities ___(7)___ already begun to notice the benefits of cleaner air in cities that have adopted electric transportation. ___(8)___ progress has been made, there is still a long way to go before renewable energy becomes the main source of power worldwide. ___(9)___ the challenges, younger generations remain optimistic about a cleaner future. ___(10)___ these efforts continue, the planet could see significant improvements within the next few decades.</div><p style=''margin-top:8px;''><strong>Elige la opción correcta para el espacio (1).</strong></p>'),
  (36, '<div class=''sim-part-tag''>Parte 7 de 7 — Texto con espacios (nivel avanzado)</div><div class=''cloze-passage''>In recent years, renewable energy sources such as solar and wind power ___(1)___ become more affordable than ever before. <mark>___(2)___</mark> fossil fuels still dominate global energy production, many countries are investing heavily in clean alternatives. Governments ___(3)___ introduced new policies to encourage citizens and businesses to reduce their carbon footprint. ___(4)___, some industries continue to resist these changes because of the high initial costs. ___(5)___ these obstacles, experts believe that renewable energy will eventually replace most fossil fuels. Critics argue, ___(6)___, that the transition should happen faster to prevent further damage to the environment. Communities ___(7)___ already begun to notice the benefits of cleaner air in cities that have adopted electric transportation. ___(8)___ progress has been made, there is still a long way to go before renewable energy becomes the main source of power worldwide. ___(9)___ the challenges, younger generations remain optimistic about a cleaner future. ___(10)___ these efforts continue, the planet could see significant improvements within the next few decades.</div><p style=''margin-top:8px;''><strong>Elige la opción correcta para el espacio (2).</strong></p>'),
  (37, '<div class=''sim-part-tag''>Parte 7 de 7 — Texto con espacios (nivel avanzado)</div><div class=''cloze-passage''>In recent years, renewable energy sources such as solar and wind power ___(1)___ become more affordable than ever before. ___(2)___ fossil fuels still dominate global energy production, many countries are investing heavily in clean alternatives. Governments <mark>___(3)___</mark> introduced new policies to encourage citizens and businesses to reduce their carbon footprint. ___(4)___, some industries continue to resist these changes because of the high initial costs. ___(5)___ these obstacles, experts believe that renewable energy will eventually replace most fossil fuels. Critics argue, ___(6)___, that the transition should happen faster to prevent further damage to the environment. Communities ___(7)___ already begun to notice the benefits of cleaner air in cities that have adopted electric transportation. ___(8)___ progress has been made, there is still a long way to go before renewable energy becomes the main source of power worldwide. ___(9)___ the challenges, younger generations remain optimistic about a cleaner future. ___(10)___ these efforts continue, the planet could see significant improvements within the next few decades.</div><p style=''margin-top:8px;''><strong>Elige la opción correcta para el espacio (3).</strong></p>'),
  (38, '<div class=''sim-part-tag''>Parte 7 de 7 — Texto con espacios (nivel avanzado)</div><div class=''cloze-passage''>In recent years, renewable energy sources such as solar and wind power ___(1)___ become more affordable than ever before. ___(2)___ fossil fuels still dominate global energy production, many countries are investing heavily in clean alternatives. Governments ___(3)___ introduced new policies to encourage citizens and businesses to reduce their carbon footprint. <mark>___(4)___</mark>, some industries continue to resist these changes because of the high initial costs. ___(5)___ these obstacles, experts believe that renewable energy will eventually replace most fossil fuels. Critics argue, ___(6)___, that the transition should happen faster to prevent further damage to the environment. Communities ___(7)___ already begun to notice the benefits of cleaner air in cities that have adopted electric transportation. ___(8)___ progress has been made, there is still a long way to go before renewable energy becomes the main source of power worldwide. ___(9)___ the challenges, younger generations remain optimistic about a cleaner future. ___(10)___ these efforts continue, the planet could see significant improvements within the next few decades.</div><p style=''margin-top:8px;''><strong>Elige la opción correcta para el espacio (4).</strong></p>'),
  (39, '<div class=''sim-part-tag''>Parte 7 de 7 — Texto con espacios (nivel avanzado)</div><div class=''cloze-passage''>In recent years, renewable energy sources such as solar and wind power ___(1)___ become more affordable than ever before. ___(2)___ fossil fuels still dominate global energy production, many countries are investing heavily in clean alternatives. Governments ___(3)___ introduced new policies to encourage citizens and businesses to reduce their carbon footprint. ___(4)___, some industries continue to resist these changes because of the high initial costs. <mark>___(5)___</mark> these obstacles, experts believe that renewable energy will eventually replace most fossil fuels. Critics argue, ___(6)___, that the transition should happen faster to prevent further damage to the environment. Communities ___(7)___ already begun to notice the benefits of cleaner air in cities that have adopted electric transportation. ___(8)___ progress has been made, there is still a long way to go before renewable energy becomes the main source of power worldwide. ___(9)___ the challenges, younger generations remain optimistic about a cleaner future. ___(10)___ these efforts continue, the planet could see significant improvements within the next few decades.</div><p style=''margin-top:8px;''><strong>Elige la opción correcta para el espacio (5).</strong></p>'),
  (40, '<div class=''sim-part-tag''>Parte 7 de 7 — Texto con espacios (nivel avanzado)</div><div class=''cloze-passage''>In recent years, renewable energy sources such as solar and wind power ___(1)___ become more affordable than ever before. ___(2)___ fossil fuels still dominate global energy production, many countries are investing heavily in clean alternatives. Governments ___(3)___ introduced new policies to encourage citizens and businesses to reduce their carbon footprint. ___(4)___, some industries continue to resist these changes because of the high initial costs. ___(5)___ these obstacles, experts believe that renewable energy will eventually replace most fossil fuels. Critics argue, <mark>___(6)___</mark>, that the transition should happen faster to prevent further damage to the environment. Communities ___(7)___ already begun to notice the benefits of cleaner air in cities that have adopted electric transportation. ___(8)___ progress has been made, there is still a long way to go before renewable energy becomes the main source of power worldwide. ___(9)___ the challenges, younger generations remain optimistic about a cleaner future. ___(10)___ these efforts continue, the planet could see significant improvements within the next few decades.</div><p style=''margin-top:8px;''><strong>Elige la opción correcta para el espacio (6).</strong></p>'),
  (41, '<div class=''sim-part-tag''>Parte 7 de 7 — Texto con espacios (nivel avanzado)</div><div class=''cloze-passage''>In recent years, renewable energy sources such as solar and wind power ___(1)___ become more affordable than ever before. ___(2)___ fossil fuels still dominate global energy production, many countries are investing heavily in clean alternatives. Governments ___(3)___ introduced new policies to encourage citizens and businesses to reduce their carbon footprint. ___(4)___, some industries continue to resist these changes because of the high initial costs. ___(5)___ these obstacles, experts believe that renewable energy will eventually replace most fossil fuels. Critics argue, ___(6)___, that the transition should happen faster to prevent further damage to the environment. Communities <mark>___(7)___</mark> already begun to notice the benefits of cleaner air in cities that have adopted electric transportation. ___(8)___ progress has been made, there is still a long way to go before renewable energy becomes the main source of power worldwide. ___(9)___ the challenges, younger generations remain optimistic about a cleaner future. ___(10)___ these efforts continue, the planet could see significant improvements within the next few decades.</div><p style=''margin-top:8px;''><strong>Elige la opción correcta para el espacio (7).</strong></p>'),
  (42, '<div class=''sim-part-tag''>Parte 7 de 7 — Texto con espacios (nivel avanzado)</div><div class=''cloze-passage''>In recent years, renewable energy sources such as solar and wind power ___(1)___ become more affordable than ever before. ___(2)___ fossil fuels still dominate global energy production, many countries are investing heavily in clean alternatives. Governments ___(3)___ introduced new policies to encourage citizens and businesses to reduce their carbon footprint. ___(4)___, some industries continue to resist these changes because of the high initial costs. ___(5)___ these obstacles, experts believe that renewable energy will eventually replace most fossil fuels. Critics argue, ___(6)___, that the transition should happen faster to prevent further damage to the environment. Communities ___(7)___ already begun to notice the benefits of cleaner air in cities that have adopted electric transportation. <mark>___(8)___</mark> progress has been made, there is still a long way to go before renewable energy becomes the main source of power worldwide. ___(9)___ the challenges, younger generations remain optimistic about a cleaner future. ___(10)___ these efforts continue, the planet could see significant improvements within the next few decades.</div><p style=''margin-top:8px;''><strong>Elige la opción correcta para el espacio (8).</strong></p>'),
  (43, '<div class=''sim-part-tag''>Parte 7 de 7 — Texto con espacios (nivel avanzado)</div><div class=''cloze-passage''>In recent years, renewable energy sources such as solar and wind power ___(1)___ become more affordable than ever before. ___(2)___ fossil fuels still dominate global energy production, many countries are investing heavily in clean alternatives. Governments ___(3)___ introduced new policies to encourage citizens and businesses to reduce their carbon footprint. ___(4)___, some industries continue to resist these changes because of the high initial costs. ___(5)___ these obstacles, experts believe that renewable energy will eventually replace most fossil fuels. Critics argue, ___(6)___, that the transition should happen faster to prevent further damage to the environment. Communities ___(7)___ already begun to notice the benefits of cleaner air in cities that have adopted electric transportation. ___(8)___ progress has been made, there is still a long way to go before renewable energy becomes the main source of power worldwide. <mark>___(9)___</mark> the challenges, younger generations remain optimistic about a cleaner future. ___(10)___ these efforts continue, the planet could see significant improvements within the next few decades.</div><p style=''margin-top:8px;''><strong>Elige la opción correcta para el espacio (9).</strong></p>'),
  (44, '<div class=''sim-part-tag''>Parte 7 de 7 — Texto con espacios (nivel avanzado)</div><div class=''cloze-passage''>In recent years, renewable energy sources such as solar and wind power ___(1)___ become more affordable than ever before. ___(2)___ fossil fuels still dominate global energy production, many countries are investing heavily in clean alternatives. Governments ___(3)___ introduced new policies to encourage citizens and businesses to reduce their carbon footprint. ___(4)___, some industries continue to resist these changes because of the high initial costs. ___(5)___ these obstacles, experts believe that renewable energy will eventually replace most fossil fuels. Critics argue, ___(6)___, that the transition should happen faster to prevent further damage to the environment. Communities ___(7)___ already begun to notice the benefits of cleaner air in cities that have adopted electric transportation. ___(8)___ progress has been made, there is still a long way to go before renewable energy becomes the main source of power worldwide. ___(9)___ the challenges, younger generations remain optimistic about a cleaner future. <mark>___(10)___</mark> these efforts continue, the planet could see significant improvements within the next few decades.</div><p style=''margin-top:8px;''><strong>Elige la opción correcta para el espacio (10).</strong></p>')
) as v(order_index, prompt)
where c.slug = 'pre-icfes' and m.title = 'Simulacro final' and qz.stage = 'main'
on conflict (quiz_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'Que los empleados se laven las manos antes de volver a trabajar',true,'Correcto: el aviso exige higiene antes de regresar al trabajo.'),(1,'Que los empleados usen guantes todo el tiempo',false,'El aviso no menciona guantes.'),(2,'Que los clientes se laven las manos antes de comer',false,'El aviso está dirigido a ''employees'', no a clientes.'),(3,'Que el baño está cerrado por mantenimiento',false,'No hay ninguna mención de cierre en el aviso.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=0 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'El vuelo se canceló definitivamente',false,'El aviso dice ''delayed'' (retrasado), no cancelado.'),(1,'El vuelo se retrasó y ahora aborda a las 3:45 PM',true,'Correcto: ''delayed'' indica retraso y se da la nueva hora de abordaje.'),(2,'El vuelo salió antes de lo previsto',false,'Es lo contrario: el vuelo se retrasó, no adelantó.'),(3,'Los pasajeros deben ir a otra puerta de embarque',false,'El aviso no menciona un cambio de puerta.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=1 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'Nadar en la piscina',false,'El aviso no prohíbe nadar, solo clavados.'),(1,'Usar protector solar cerca del agua',false,'El aviso no menciona protector solar.'),(2,'Lanzarte de cabeza (clavados) porque el agua es poco profunda',true,'Correcto: ''no diving'' prohíbe los clavados, justamente porque el agua es poco profunda.'),(3,'Llevar toalla a la piscina',false,'El aviso no menciona toallas.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=2 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'Que los visitantes hablen en voz baja o guarden silencio en esa zona',true,'Correcto: ''silence please'' pide silencio en el área de estudio.'),(1,'Que los visitantes no lleven libros propios',false,'El aviso no menciona libros propios.'),(2,'Que los visitantes reserven una mesa con anticipación',false,'El aviso no menciona reservas.'),(3,'Que la zona está cerrada por remodelación',false,'No hay ninguna mención de cierre.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=3 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'Esperar a que abran esa puerta en unos minutos',false,'El aviso no indica que se reparará pronto, solo que está fuera de servicio.'),(1,'Forzar la puerta para entrar',false,'El aviso no sugiere forzar nada; al contrario, indica usar otra entrada.'),(2,'Reportar el daño en información al cliente',false,'El aviso no pide reportar nada, solo redirige al visitante.'),(3,'Usar otra entrada porque esta puerta no funciona',true,'Correcto: ''out of order'' significa que no funciona, y el aviso indica usar otra entrada.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=4 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'menu',false,'''Menu'' no encaja con este enunciado.'),(1,'brochure',false,'''Brochure'' no encaja con este enunciado.'),(2,'invoice',false,'''Invoice'' no encaja con este enunciado.'),(3,'schedule',false,'''Schedule'' no encaja con este enunciado.'),(4,'voucher',false,'''Voucher'' no encaja con este enunciado.'),(5,'itinerary',true,'Correcto: ''itinerary'' es el documento con los horarios del viaje.'),(6,'receipt',false,'''Receipt'' no encaja con este enunciado.'),(7,'certificate',false,'''Certificate'' no encaja con este enunciado.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=5 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'menu',true,'Correcto: ''menu'' es la carta de comidas y bebidas.'),(1,'brochure',false,'''Brochure'' no encaja con este enunciado.'),(2,'invoice',false,'''Invoice'' no encaja con este enunciado.'),(3,'schedule',false,'''Schedule'' no encaja con este enunciado.'),(4,'voucher',false,'''Voucher'' no encaja con este enunciado.'),(5,'itinerary',false,'''Itinerary'' no encaja con este enunciado.'),(6,'receipt',false,'''Receipt'' no encaja con este enunciado.'),(7,'certificate',false,'''Certificate'' no encaja con este enunciado.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=6 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'menu',false,'''Menu'' no encaja con este enunciado.'),(1,'brochure',false,'''Brochure'' no encaja con este enunciado.'),(2,'invoice',false,'''Invoice'' no encaja con este enunciado.'),(3,'schedule',false,'''Schedule'' no encaja con este enunciado.'),(4,'voucher',false,'''Voucher'' no encaja con este enunciado.'),(5,'itinerary',false,'''Itinerary'' no encaja con este enunciado.'),(6,'receipt',true,'Correcto: ''receipt'' es el recibo que prueba que ya pagaste.'),(7,'certificate',false,'''Certificate'' no encaja con este enunciado.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=7 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'menu',false,'''Menu'' no encaja con este enunciado.'),(1,'brochure',false,'''Brochure'' no encaja con este enunciado.'),(2,'invoice',false,'''Invoice'' no encaja con este enunciado.'),(3,'schedule',false,'''Schedule'' no encaja con este enunciado.'),(4,'voucher',true,'Correcto: ''voucher'' es el vale que puedes canjear por un beneficio.'),(5,'itinerary',false,'''Itinerary'' no encaja con este enunciado.'),(6,'receipt',false,'''Receipt'' no encaja con este enunciado.'),(7,'certificate',false,'''Certificate'' no encaja con este enunciado.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=8 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'menu',false,'''Menu'' no encaja con este enunciado.'),(1,'brochure',false,'''Brochure'' no encaja con este enunciado.'),(2,'invoice',false,'''Invoice'' no encaja con este enunciado.'),(3,'schedule',false,'''Schedule'' no encaja con este enunciado.'),(4,'voucher',false,'''Voucher'' no encaja con este enunciado.'),(5,'itinerary',false,'''Itinerary'' no encaja con este enunciado.'),(6,'receipt',false,'''Receipt'' no encaja con este enunciado.'),(7,'certificate',true,'Correcto: ''certificate'' es el documento que certifica que terminaste un curso.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=9 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'It''s five kilometers.',false,'Fuera de tema — habla de distancia.'),(1,'I already ate, thanks.',true,'Correcto: responde a la invitación de forma coherente.'),(2,'He''s my cousin.',false,'Fuera de tema — habla de otra persona.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=10 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'It''s Tuesday today.',false,'Fuera de tema — habla del día de la semana.'),(1,'I prefer tea.',false,'Fuera de tema — habla de una preferencia.'),(2,'They''re on the kitchen table.',true,'Correcto: responde dónde están las llaves.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=11 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'Yes, I didn''t sleep well.',true,'Correcto: responde a la observación sobre su estado.'),(1,'It''s made of cotton.',false,'Fuera de tema — describe un material.'),(2,'Turn right here.',false,'Fuera de tema — son indicaciones de dirección.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=12 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'He lives nearby.',false,'Fuera de tema — habla de otra persona.'),(1,'It closes at nine.',false,'Fuera de tema — habla de un horario.'),(2,'I really like Math.',true,'Correcto: responde cuál es la materia favorita.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=13 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'I''m nineteen years old.',false,'Fuera de tema — habla de edad.'),(1,'Sure, sorry about that.',true,'Correcto: acepta la petición de bajar el volumen.'),(2,'The train leaves soon.',false,'Fuera de tema — habla de un horario de tren.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=14 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'to',true,'Correcto: ''go to'' + lugar.'),(1,'at',false,'No es la opción que mejor encaja en este espacio; revisa el contexto cercano.'),(2,'in',false,'No es la opción que mejor encaja en este espacio; revisa el contexto cercano.'),(3,'for',false,'No es la opción que mejor encaja en este espacio; revisa el contexto cercano.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=15 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'in',false,'No es la opción que mejor encaja en este espacio; revisa el contexto cercano.'),(1,'on',false,'No es la opción que mejor encaja en este espacio; revisa el contexto cercano.'),(2,'at',true,'Correcto: ''arrive at'' + una hora exacta.'),(3,'for',false,'No es la opción que mejor encaja en este espacio; revisa el contexto cercano.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=16 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'in',true,'Correcto: ''help her in the garden'' indica el lugar donde ayudaron.'),(1,'with',false,'No es la opción que mejor encaja en este espacio; revisa el contexto cercano.'),(2,'on',false,'No es la opción que mejor encaja en este espacio; revisa el contexto cercano.'),(3,'by',false,'No es la opción que mejor encaja en este espacio; revisa el contexto cercano.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=17 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'to',true,'Correcto: ''showed us how to plant'' — infinitivo con ''to''.'),(1,'for',false,'No es la opción que mejor encaja en este espacio; revisa el contexto cercano.'),(2,'that',false,'No es la opción que mejor encaja en este espacio; revisa el contexto cercano.'),(3,'of',false,'No es la opción que mejor encaja en este espacio; revisa el contexto cercano.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=18 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'its',false,'No es la opción que mejor encaja en este espacio; revisa el contexto cercano.'),(1,'our',true,'Correcto: el sujeto es ''we'', entonces el posesivo es ''our''.'),(2,'their',false,'No es la opción que mejor encaja en este espacio; revisa el contexto cercano.'),(3,'his',false,'No es la opción que mejor encaja en este espacio; revisa el contexto cercano.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=19 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'her',false,'No es la opción que mejor encaja en este espacio; revisa el contexto cercano.'),(1,'his',true,'Correcto: el sujeto es ''my brother'' (he), entonces el posesivo es ''his''.'),(2,'their',false,'No es la opción que mejor encaja en este espacio; revisa el contexto cercano.'),(3,'our',false,'No es la opción que mejor encaja en este espacio; revisa el contexto cercano.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=20 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'in',false,'No es la opción que mejor encaja en este espacio; revisa el contexto cercano.'),(1,'on',true,'Correcto: ''on the porch'' — se usa ''on'' con superficies como un porche.'),(2,'at',false,'No es la opción que mejor encaja en este espacio; revisa el contexto cercano.'),(3,'by',false,'No es la opción que mejor encaja en este espacio; revisa el contexto cercano.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=21 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'of',true,'Correcto: ''a basket of vegetables'' — ''of'' indica el contenido.'),(1,'in',false,'No es la opción que mejor encaja en este espacio; revisa el contexto cercano.'),(2,'for',false,'No es la opción que mejor encaja en este espacio; revisa el contexto cercano.'),(3,'at',false,'No es la opción que mejor encaja en este espacio; revisa el contexto cercano.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=22 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'In a small town in Colombia',true,'Correcto: el texto dice que nació en un pueblo pequeño de Colombia.'),(1,'In Bogotá',false,'Esta opción no coincide con lo que dice el texto explícitamente.'),(2,'In a different country',false,'Esta opción no coincide con lo que dice el texto explícitamente.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=23 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'Ten years old',true,'Correcto: el texto dice ''when she was ten years old''.'),(1,'Nineteen years old',false,'Esta opción no coincide con lo que dice el texto explícitamente.'),(2,'Two years old',false,'Esta opción no coincide con lo que dice el texto explícitamente.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=24 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'So her parents could find better jobs',true,'Correcto: el texto dice que se mudaron para que sus padres consiguieran mejores trabajos.'),(1,'To be closer to a university',false,'Esta opción no coincide con lo que dice el texto explícitamente.'),(2,'Because of the weather',false,'Esta opción no coincide con lo que dice el texto explícitamente.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=25 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'History',false,'Esta opción no coincide con lo que dice el texto explícitamente.'),(1,'Mathematics',true,'Correcto: el texto dice que amaba las matemáticas.'),(2,'Art',false,'Esta opción no coincide con lo que dice el texto explícitamente.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=26 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'A scholarship abroad',false,'Esta opción no coincide con lo que dice el texto explícitamente.'),(1,'First place in a national mathematics competition',true,'Correcto: el texto dice que ganó el primer puesto en una competencia nacional de matemáticas.'),(2,'A teaching award',false,'Esta opción no coincide con lo que dice el texto explícitamente.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=27 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'Engineering',true,'Correcto: el texto dice que estudió ingeniería con una beca.'),(1,'Medicine',false,'Esta opción no coincide con lo que dice el texto explícitamente.'),(2,'Law',false,'Esta opción no coincide con lo que dice el texto explícitamente.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=28 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'She studies for exams',false,'Esta opción no coincide con lo que dice el texto explícitamente.'),(1,'She works as a volunteer teacher',true,'Correcto: el texto dice que hoy es profesora voluntaria los fines de semana.'),(2,'She travels around the country',false,'Esta opción no coincide con lo que dice el texto explícitamente.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=29 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'Give instructions on how to train a pet',false,'Esta opción no se sostiene con las pistas del texto; revisa el tono y las ideas generales.'),(1,'Explain why pets matter emotionally to their owners',true,'Correcto: el texto explica, en conjunto, por qué las mascotas importan emocionalmente a sus dueños.'),(2,'Compare different types of pets',false,'Esta opción no se sostiene con las pistas del texto; revisa el tono y las ideas generales.'),(3,'Warn people against getting a pet',false,'Esta opción no se sostiene con las pistas del texto; revisa el tono y las ideas generales.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=30 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'They are usually the easiest part of pet ownership',false,'Esta opción no se sostiene con las pistas del texto; revisa el tono y las ideas generales.'),(1,'They require little effort from the owner',false,'Esta opción no se sostiene con las pistas del texto; revisa el tono y las ideas generales.'),(2,'They can be demanding and require patience',true,'Correcto: el texto dice que requiere tiempo, dinero y paciencia, ''especially during the first few months''.'),(3,'They are mostly focused on choosing a pet''s name',false,'Esta opción no se sostiene con las pistas del texto; revisa el tono y las ideas generales.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=31 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'It is mostly about entertainment',false,'Esta opción no se sostiene con las pistas del texto; revisa el tono y las ideas generales.'),(1,'It goes beyond a simple hobby and becomes emotional',true,'Correcto: el texto dice explícitamente que es ''much more than a hobby''.'),(2,'It usually fades over time',false,'Esta opción no se sostiene con las pistas del texto; revisa el tono y las ideas generales.'),(3,'It is more common in wealthy families',false,'Esta opción no se sostiene con las pistas del texto; revisa el tono y las ideas generales.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=32 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'Completely negative and discouraging',false,'Esta opción no se sostiene con las pistas del texto; revisa el tono y las ideas generales.'),(1,'Neutral, acknowledging challenges but valuing the outcome',true,'Correcto: reconoce la responsabilidad (''serious commitment'') pero concluye que vale la pena.'),(2,'Humorous and sarcastic',false,'Esta opción no se sostiene con las pistas del texto; revisa el tono y las ideas generales.'),(3,'Purely scientific, without opinion',false,'Esta opción no se sostiene con las pistas del texto; revisa el tono y las ideas generales.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=33 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'To prove that pets are more intelligent than believed',false,'Esta opción no se sostiene con las pistas del texto; revisa el tono y las ideas generales.'),(1,'To support the idea that pets provide real, measurable benefits',true,'Correcto: se usa el dato científico para respaldar el beneficio emocional/físico ya mencionado.'),(2,'To criticize pet owners who don''t visit the vet',false,'Esta opción no se sostiene con las pistas del texto; revisa el tono y las ideas generales.'),(3,'To explain how pets communicate with humans',false,'Esta opción no se sostiene con las pistas del texto; revisa el tono y las ideas generales.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=34 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'have',true,'Correcto: el sujeto (''energy sources'') es plural, se usa ''have''.'),(1,'has',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.'),(2,'had',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.'),(3,'having',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=35 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'Because',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.'),(1,'Although',true,'Correcto: ''Although'' introduce el contraste con lo que sigue.'),(2,'So',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.'),(3,'Unless',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=36 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'have',true,'Correcto: el sujeto ''governments'' es plural, se usa ''have introduced''.'),(1,'has',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.'),(2,'is',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.'),(3,'are',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=37 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'Therefore',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.'),(1,'However',true,'Correcto: ''However'' contrasta las políticas con la resistencia de algunas industrias.'),(2,'Meanwhile',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.'),(3,'Because',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=38 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'Despite',true,'Correcto: ''Despite'' se sigue de un sustantivo (''these obstacles'').'),(1,'Although',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.'),(2,'Because',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.'),(3,'Unless',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=39 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'therefore',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.'),(1,'however',true,'Correcto: ''however'' se inserta para matizar/contrastar dentro de la oración.'),(2,'despite',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.'),(3,'because',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=40 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'have',true,'Correcto: el sujeto ''communities'' es plural, se usa ''have begun''.'),(1,'has',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.'),(2,'is',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.'),(3,'are',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=41 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'Because',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.'),(1,'Although',true,'Correcto: ''Although'' introduce el contraste entre el progreso y lo que falta.'),(2,'So',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.'),(3,'Unless',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=42 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'Despite',true,'Correcto: ''Despite'' se sigue de un sustantivo (''the challenges'').'),(1,'Although',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.'),(2,'Because',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.'),(3,'Unless',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=43 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;

insert into public.quiz_choices (question_id, order_index, choice_text, is_correct, feedback)
select qq.id, v.order_index, v.choice_text, v.is_correct, v.feedback
from public.quiz_questions qq join public.quizzes qz on qz.id=qq.quiz_id join public.modules m on m.id=qz.module_id join public.courses c on c.id=m.course_id
cross join (values (0,'If',true,'Correcto: ''If'' introduce la condición para que el planeta mejore.'),(1,'Unless',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.'),(2,'Despite',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.'),(3,'Because',false,'No es la opción que mejor encaja; revisa si el espacio pide concordancia verbal o un conector lógico.')) as v(order_index,choice_text,is_correct,feedback)
where c.slug='pre-icfes' and m.title='Simulacro final' and qq.order_index=44 and exists(select 1 from public.quizzes qz2 where qz2.id=qq.quiz_id and qz2.stage='main')
on conflict (question_id, order_index) do nothing;